### ISSUE TITLE
Monorepo for reffects & reffects-store & co.

### ISSUE THREAD

**Issue by alexhoma** [trovit/reffects#4]
Today we're using two repositories to work with reffects (`reffects` and `reffects-store`). Every time we have a change, we need to test not only the automated unit tests but also some manual checks that everything between libraries is working as expected (not always, but sometimes this is necessary). Also, when introducing a feature, sometimes we need to release both projects separately in different repositories.

I think it could be interesting to study the development of reffects & co. as a monorepository, to improve the development experience, improve the release process and have more close those two libraries (and other that could be related with reffects, like some predefined effects or coeffects).
Also, It's true that you can use `reffects` without the store, but this could not be a problem since once they are released, they can be imported as a separate different packages. So if you do not need `reffects-store` simply don't import it.

**Resources:**
 - A project that can help us through this would be Lerna https://github.com/lerna/lerna
 - Some libraries using these approach are: 
  - https://github.com/zerobias/effector (using lerna)
  - https://github.com/facebook/react (not using lerna)
  - https://github.com/developit/unistore (not using lerna)

As a final thought, this would ease us to have an `examples` directory or a `playground` that could use the current development state of both `reffects` and `reffects-store` to play with it when necessary.

**Comment by mariosanchez** [comment]
I think it's a good idea since will be easier to manage all the libraries related with reffects, also have common example cases very useful to test and demonstrate how to use them all together.

**Comment by mariosanchez** [comment]
https://github.com/trovit/reffects/commit/bd20e29d9275566d948792a0e8e1511466f01777
